export const config = {
			canvas: {
				id: undefined,
				width: 500,
				height: 500,
			},
			main: {
				frameRate: 30,
				numParticles: 100,
				speed: 0.2,
				mouseDistance: 100,
				fillStyle: '#000',
				isFullScreen: true,
				isResponsive: true,
			},
			particles: {
				shape: 'circle',
				fillStyle: '#ff0000',
				randomFill: true,
				noFill: false,
				stroke: true,
				size: 2,
				randomSize: true,
				draw: true,
				collision: false,
				opacity: 1,
			},
			lines: {
				connectDistance: 100,
				strokeStyle: '#ffffff',
				draw: true,
				lineWidth: 0.5,
				opacity: 1,
			},
		};